--- #YAML:1.0
name: InSilicoSpectro
version: 1.2.5
author:
  - Alexandre Masselot <alexandre.masselot@genebio.com>, Jacques Colinge <Jacques.Colinge@fh-hagenberg.at>
abstract: InSilico Mass Spectrometry toolkit
license: lgpl
generated_by: Module::Build version 0.2611, without YAML.pm
